### ISSUE TITLE
Docs reference to respective eslint rule

### ISSUE THREAD

**Issue by MichalBryxi** [OTA-Insight/ember-computed-macro-codemod#2]
The sentence of README that reads:

> The recommended Ember ESLint config [discourages computed property macros](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-computed-macros.md#configuration) for class based syntax.

Points currently to: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/require-computed-macros.md#configuration

Which is about using `computed.*` helpers instead of doing ad-hoc `computed() { // do your work here }`.

I believe this codemod is refering more to the [ember/no-computed-properties-in-native-classes][1] as this codemod changes (for example) `@readOnly` to `get() { ... }` and thus fixes said rule in native classes.

Or am I missing something?

[1]: https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/no-computed-properties-in-native-classes.md

**Comment by IgnaceMaes** [comment]
The currently referenced rule mentions

> ... in the Ember Octane world, the better improvement would be to keep the native getter and use tracked properties instead of computed properties.

But linking to the actual linting rule that has an impact on this would make way more sense indeed!
